/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crypto;

/**
 *
 * @author marcus
 */
public class MainGUI extends javax.swing.JFrame {
    
    ISBNandCard ISBNandCardObj = new ISBNandCard();
    ModularArithmetic modA = new ModularArithmetic();
    BCH bch = new BCH();
//    BCH w3 = new BCH();
    BruteForcePassword bruteforce = new BruteForcePassword();
    FermatFactorization fermat = new FermatFactorization();
    DixonFactorization dixon = new DixonFactorization();

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Tabs = new javax.swing.JTabbedPane();
        ISBNandCard = new javax.swing.JPanel();
        isbn = new javax.swing.JLabel();
        CardNumber = new javax.swing.JLabel();
        isbnField = new javax.swing.JTextField();
        cardField = new javax.swing.JTextField();
        isbnButton = new javax.swing.JButton();
        cardButton = new javax.swing.JButton();
        ModularArithmatic = new javax.swing.JPanel();
        xLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        xField = new javax.swing.JTextField();
        yField = new javax.swing.JTextField();
        modAdd = new javax.swing.JButton();
        modSubtract = new javax.swing.JButton();
        modMultiply = new javax.swing.JButton();
        modDivide = new javax.swing.JButton();
        modLabel = new javax.swing.JLabel();
        modField = new javax.swing.JTextField();
        BCH = new javax.swing.JPanel();
        bchField = new javax.swing.JTextField();
        decodeBch = new javax.swing.JButton();
        enterBchNum = new javax.swing.JLabel();
        bchDecoder = new javax.swing.JLabel();
        sixDigitsBCH = new javax.swing.JLabel();
        sixDigitsBCHfield = new javax.swing.JTextField();
        generate4Digits = new javax.swing.JButton();
        calcBchParity = new javax.swing.JLabel();
        BruteForce = new javax.swing.JPanel();
        genPass = new javax.swing.JButton();
        enterPass = new javax.swing.JLabel();
        passField = new javax.swing.JTextField();
        showSHA1 = new javax.swing.JButton();
        bruteForce = new javax.swing.JButton();
        createrandpass = new javax.swing.JLabel();
        dispSHA1 = new javax.swing.JLabel();
        bruteLabel = new javax.swing.JLabel();
        enterPassButton = new javax.swing.JButton();
        entersha1hash = new javax.swing.JLabel();
        SHA1hash = new javax.swing.JTextField();
        EnterHash = new javax.swing.JButton();
        Fermat = new javax.swing.JPanel();
        FermatFact = new javax.swing.JButton();
        FermatInput = new javax.swing.JTextField();
        bigintlabel = new javax.swing.JLabel();
        Dixon = new javax.swing.JPanel();
        DixonFact = new javax.swing.JButton();
        DixonInput = new javax.swing.JTextField();
        intlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        clearOut = new javax.swing.JButton();
        clearAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        isbn.setText("ISBN:");

        CardNumber.setText("Card number:");

        isbnButton.setText("Check ISBN");
        isbnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isbnButtonMouseClicked(evt);
            }
        });

        cardButton.setText("Check card");
        cardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ISBNandCardLayout = new javax.swing.GroupLayout(ISBNandCard);
        ISBNandCard.setLayout(ISBNandCardLayout);
        ISBNandCardLayout.setHorizontalGroup(
            ISBNandCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ISBNandCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ISBNandCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ISBNandCardLayout.createSequentialGroup()
                        .addComponent(isbn)
                        .addGap(77, 77, 77)
                        .addComponent(isbnField))
                    .addGroup(ISBNandCardLayout.createSequentialGroup()
                        .addComponent(CardNumber)
                        .addGap(21, 21, 21)
                        .addComponent(cardField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(ISBNandCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(isbnButton)
                    .addComponent(cardButton))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        ISBNandCardLayout.setVerticalGroup(
            ISBNandCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ISBNandCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ISBNandCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbn)
                    .addComponent(isbnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbnButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ISBNandCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardNumber)
                    .addComponent(cardField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardButton))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        Tabs.addTab("ISBN and Card Check", ISBNandCard);

        xLabel.setText("X :");

        yLabel.setText("Y :");

        modAdd.setText("Add");
        modAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modAddMouseClicked(evt);
            }
        });

        modSubtract.setText("Subtract");
        modSubtract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modSubtractMouseClicked(evt);
            }
        });

        modMultiply.setText("Multiply");
        modMultiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modMultiplyMouseClicked(evt);
            }
        });

        modDivide.setText("Divide");
        modDivide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modDivideMouseClicked(evt);
            }
        });

        modLabel.setText("Mod :");

        javax.swing.GroupLayout ModularArithmaticLayout = new javax.swing.GroupLayout(ModularArithmatic);
        ModularArithmatic.setLayout(ModularArithmaticLayout);
        ModularArithmaticLayout.setHorizontalGroup(
            ModularArithmaticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModularArithmaticLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModularArithmaticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModularArithmaticLayout.createSequentialGroup()
                        .addGroup(ModularArithmaticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModularArithmaticLayout.createSequentialGroup()
                                .addComponent(yLabel)
                                .addGap(34, 34, 34)
                                .addComponent(yField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ModularArithmaticLayout.createSequentialGroup()
                                .addComponent(xLabel)
                                .addGap(34, 34, 34)
                                .addComponent(xField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(ModularArithmaticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(ModularArithmaticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ModularArithmaticLayout.createSequentialGroup()
                        .addComponent(modLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        ModularArithmaticLayout.setVerticalGroup(
            ModularArithmaticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModularArithmaticLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModularArithmaticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xLabel)
                    .addComponent(xField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modAdd)
                    .addComponent(modMultiply))
                .addGap(16, 16, 16)
                .addGroup(ModularArithmaticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modDivide)
                    .addComponent(modSubtract)
                    .addComponent(yField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yLabel))
                .addGap(18, 18, 18)
                .addGroup(ModularArithmaticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modLabel)
                    .addComponent(modField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        Tabs.addTab("Modular Arithmetic", ModularArithmatic);

        decodeBch.setText("Decode BCH");
        decodeBch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decodeBchMouseClicked(evt);
            }
        });

        enterBchNum.setText("Enter 10 digits:");

        bchDecoder.setText("BCH Decoder");

        sixDigitsBCH.setText("Enter 6 digits:");

        generate4Digits.setText("Generate digits");
        generate4Digits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generate4DigitsMouseClicked(evt);
            }
        });

        calcBchParity.setText("BCH generator");

        javax.swing.GroupLayout BCHLayout = new javax.swing.GroupLayout(BCH);
        BCH.setLayout(BCHLayout);
        BCHLayout.setHorizontalGroup(
            BCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BCHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calcBchParity)
                    .addComponent(bchDecoder)
                    .addGroup(BCHLayout.createSequentialGroup()
                        .addGroup(BCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BCHLayout.createSequentialGroup()
                                .addComponent(enterBchNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bchField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BCHLayout.createSequentialGroup()
                                .addComponent(sixDigitsBCH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sixDigitsBCHfield, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(BCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generate4Digits)
                            .addComponent(decodeBch))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        BCHLayout.setVerticalGroup(
            BCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BCHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calcBchParity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixDigitsBCH)
                    .addComponent(sixDigitsBCHfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generate4Digits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bchDecoder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterBchNum)
                    .addComponent(bchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decodeBch))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        Tabs.addTab("BCH", BCH);

        genPass.setText("Gen Pass");
        genPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genPassMouseClicked(evt);
            }
        });

        enterPass.setText("Enter password:");

        showSHA1.setText("Show SHA1");
        showSHA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showSHA1MouseClicked(evt);
            }
        });

        bruteForce.setText("Brute Force");
        bruteForce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bruteForceMouseClicked(evt);
            }
        });

        createrandpass.setText("Create random pass:");

        dispSHA1.setText("Display SHA1:");

        bruteLabel.setText("Brute Force pass:");

        enterPassButton.setText("Enter pass");
        enterPassButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterPassButtonMouseClicked(evt);
            }
        });

        entersha1hash.setText("Enter SHA1 hash:");

        EnterHash.setText("Enter Hash");
        EnterHash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterHashMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BruteForceLayout = new javax.swing.GroupLayout(BruteForce);
        BruteForce.setLayout(BruteForceLayout);
        BruteForceLayout.setHorizontalGroup(
            BruteForceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BruteForceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BruteForceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BruteForceLayout.createSequentialGroup()
                        .addGroup(BruteForceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterPass)
                            .addComponent(entersha1hash))
                        .addGap(37, 37, 37)
                        .addGroup(BruteForceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BruteForceLayout.createSequentialGroup()
                                .addComponent(SHA1hash, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EnterHash))
                            .addGroup(BruteForceLayout.createSequentialGroup()
                                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enterPassButton))))
                    .addGroup(BruteForceLayout.createSequentialGroup()
                        .addGroup(BruteForceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createrandpass)
                            .addComponent(dispSHA1)
                            .addComponent(bruteLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BruteForceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bruteForce)
                            .addComponent(showSHA1)
                            .addComponent(genPass))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        BruteForceLayout.setVerticalGroup(
            BruteForceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BruteForceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BruteForceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterPass)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterPassButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BruteForceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entersha1hash)
                    .addComponent(SHA1hash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterHash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BruteForceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createrandpass)
                    .addComponent(genPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BruteForceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dispSHA1)
                    .addComponent(showSHA1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BruteForceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bruteLabel)
                    .addComponent(bruteForce))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        Tabs.addTab("Brute Force", BruteForce);

        FermatFact.setText("Fermat factorization");
        FermatFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FermatFactMouseClicked(evt);
            }
        });

        bigintlabel.setText("Enter an integer:");

        javax.swing.GroupLayout FermatLayout = new javax.swing.GroupLayout(Fermat);
        Fermat.setLayout(FermatLayout);
        FermatLayout.setHorizontalGroup(
            FermatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FermatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bigintlabel)
                .addGap(85, 85, 85)
                .addGroup(FermatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FermatFact)
                    .addComponent(FermatInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        FermatLayout.setVerticalGroup(
            FermatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FermatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FermatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bigintlabel)
                    .addComponent(FermatInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FermatFact)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        Tabs.addTab("Fermat", Fermat);

        DixonFact.setText("Dixon factorization");
        DixonFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DixonFactMouseClicked(evt);
            }
        });

        intlabel.setText("Enter an integer:");

        javax.swing.GroupLayout DixonLayout = new javax.swing.GroupLayout(Dixon);
        Dixon.setLayout(DixonLayout);
        DixonLayout.setHorizontalGroup(
            DixonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DixonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(intlabel)
                .addGap(84, 84, 84)
                .addGroup(DixonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DixonFact, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DixonInput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        DixonLayout.setVerticalGroup(
            DixonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DixonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DixonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intlabel)
                    .addComponent(DixonInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DixonFact)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        Tabs.addTab("Dixon", Dixon);

        outputArea.setColumns(20);
        outputArea.setRows(10);
        jScrollPane1.setViewportView(outputArea);

        clearOut.setText("Clear Output");
        clearOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearOutMouseClicked(evt);
            }
        });

        clearAll.setText("Clear All Fields");
        clearAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearAllMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(clearOut)
                        .addGap(18, 18, 18)
                        .addComponent(clearAll))
                    .addComponent(jScrollPane1)
                    .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearOut)
                    .addComponent(clearAll))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isbnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isbnButtonMouseClicked
        outputArea.setText(ISBNandCardObj.isbnCheck(isbnField.getText()));
    }//GEN-LAST:event_isbnButtonMouseClicked

    private void modAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modAddMouseClicked
        outputArea.setText(modA.checkInputAndCallFunc(xField.getText(), yField.getText(), modField.getText(), '+'));
    }//GEN-LAST:event_modAddMouseClicked

    private void modMultiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modMultiplyMouseClicked
        outputArea.setText(modA.checkInputAndCallFunc(xField.getText(), yField.getText(), modField.getText(), '*'));
    }//GEN-LAST:event_modMultiplyMouseClicked

    private void modDivideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modDivideMouseClicked
        outputArea.setText(modA.checkInputAndCallFunc(xField.getText(), yField.getText(), modField.getText(), '/'));
    }//GEN-LAST:event_modDivideMouseClicked

    private void modSubtractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modSubtractMouseClicked
        outputArea.setText(modA.checkInputAndCallFunc(xField.getText(), yField.getText(), modField.getText(), '-'));
    }//GEN-LAST:event_modSubtractMouseClicked

    private void cardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardButtonMouseClicked
        outputArea.setText(ISBNandCardObj.cardNumCheck(cardField.getText()));
    }//GEN-LAST:event_cardButtonMouseClicked

    private void generate4DigitsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generate4DigitsMouseClicked
        outputArea.setText(bch.bchGenerator(sixDigitsBCHfield.getText()));
    }//GEN-LAST:event_generate4DigitsMouseClicked

    private void decodeBchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decodeBchMouseClicked
        outputArea.setText(bch.bchDecoder(bchField.getText()));
    }//GEN-LAST:event_decodeBchMouseClicked

    private void clearOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearOutMouseClicked
        outputArea.setText("");
    }//GEN-LAST:event_clearOutMouseClicked

    private void clearAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearAllMouseClicked
        isbnField.setText("");
        cardField.setText("");
        xField.setText("");
        yField.setText("");
        modField.setText("");
        sixDigitsBCHfield.setText("");
        bchField.setText("");
        passField.setText("");
        SHA1hash.setText("");
        FermatInput.setText("");
        DixonInput.setText("");
        outputArea.setText("");
    }//GEN-LAST:event_clearAllMouseClicked

    private void genPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genPassMouseClicked
        outputArea.setText(bruteforce.genPass());
    }//GEN-LAST:event_genPassMouseClicked

    private void showSHA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showSHA1MouseClicked
        outputArea.setText(bruteforce.getSHA1hash());
    }//GEN-LAST:event_showSHA1MouseClicked

    private void bruteForceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bruteForceMouseClicked
        for(int i = 0; i < 8; i++){  // AFK benchmarking
            long timer; 
            timer = System.nanoTime();
//            outputArea.setText(bruteforce.bruteForce());
            outputArea.setText(bruteforce.RBF(""));
            timer = System.nanoTime() - timer;
            System.out.println("Time taken is " + timer + "  nanoseconds");
        }
    }//GEN-LAST:event_bruteForceMouseClicked

    private void enterPassButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterPassButtonMouseClicked
        String newPass = passField.getText();
        bruteforce.setPassword(newPass);
        outputArea.setText(newPass);
    }//GEN-LAST:event_enterPassButtonMouseClicked

    private void EnterHashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterHashMouseClicked
        String newHash = SHA1hash.getText();
        bruteforce.setSHA1hash(newHash);
        outputArea.setText(newHash);
    }//GEN-LAST:event_EnterHashMouseClicked

    private void FermatFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FermatFactMouseClicked
        outputArea.setText(fermat.callFermat(FermatInput.getText()));
    }//GEN-LAST:event_FermatFactMouseClicked

    private void DixonFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DixonFactMouseClicked
        outputArea.setText(dixon.callDixon(DixonInput.getText()));
    }//GEN-LAST:event_DixonFactMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BCH;
    private javax.swing.JPanel BruteForce;
    private javax.swing.JLabel CardNumber;
    private javax.swing.JPanel Dixon;
    private javax.swing.JButton DixonFact;
    private javax.swing.JTextField DixonInput;
    private javax.swing.JButton EnterHash;
    private javax.swing.JPanel Fermat;
    private javax.swing.JButton FermatFact;
    private javax.swing.JTextField FermatInput;
    private javax.swing.JPanel ISBNandCard;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel ModularArithmatic;
    private javax.swing.JTextField SHA1hash;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JLabel bchDecoder;
    private javax.swing.JTextField bchField;
    private javax.swing.JLabel bigintlabel;
    private javax.swing.JButton bruteForce;
    private javax.swing.JLabel bruteLabel;
    private javax.swing.JLabel calcBchParity;
    private javax.swing.JButton cardButton;
    private javax.swing.JTextField cardField;
    private javax.swing.JButton clearAll;
    private javax.swing.JButton clearOut;
    private javax.swing.JLabel createrandpass;
    private javax.swing.JButton decodeBch;
    private javax.swing.JLabel dispSHA1;
    private javax.swing.JLabel enterBchNum;
    private javax.swing.JLabel enterPass;
    private javax.swing.JButton enterPassButton;
    private javax.swing.JLabel entersha1hash;
    private javax.swing.JButton genPass;
    private javax.swing.JButton generate4Digits;
    private javax.swing.JLabel intlabel;
    private javax.swing.JLabel isbn;
    private javax.swing.JButton isbnButton;
    private javax.swing.JTextField isbnField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modAdd;
    private javax.swing.JButton modDivide;
    private javax.swing.JTextField modField;
    private javax.swing.JLabel modLabel;
    private javax.swing.JButton modMultiply;
    private javax.swing.JButton modSubtract;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JTextField passField;
    private javax.swing.JButton showSHA1;
    private javax.swing.JLabel sixDigitsBCH;
    private javax.swing.JTextField sixDigitsBCHfield;
    private javax.swing.JTextField xField;
    private javax.swing.JLabel xLabel;
    private javax.swing.JTextField yField;
    private javax.swing.JLabel yLabel;
    // End of variables declaration//GEN-END:variables
}
